<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://ros.org/wiki/xacro">

 <!-- Kamera boyutları için xacro değişkenleri -->
    <xacro:property name="lidar_radius" value="0.08"/>
    <xacro:property name="lidar_length" value="0.05"/>
    <!-- <xacro:property name="camera_height" value="0.05"/> -->

    <link name = "lidar_link">
        <visual>
            <geometry>
                <cylinder radius = "${lidar_radius}" length = "${lidar_length}"/>
            </geometry>
            <origin xyz = "0 0 0 " rpy = "0 0 0" /> <!--bu şekilde bir gösterim ile tekerimi 90 derece döndürmeyi sağlarım-->
            <material name = "grey" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius = "${lidar_radius}" length = "${lidar_length}"/>
            </geometry>
            <origin xyz = "0 0 0 " rpy = "0 0 0" /> <!--bu şekilde bir gösterim ile tekerimi 90 derece döndürmeyi sağlarım-->
        </collision>

        <xacro:cylinder_inertia m = "0.2" r = "${2*lidar_radius}" 
                                          h = "${2*lidar_length}" 
                                          xyz = "0 0 0"
                                          rpy = "0 0 0" />
                                              <!--burada da 2* ile genişeltmeler yaparak eylemsilik momentini arttırıp daha stabil bir 
                                              durum elde etmiş olurum-->
        </link>

       <!-- Kamera ve base_link arasında sabit bağlantı (joint) -->
    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0 0 ${(base_height / 2) + (lidar_length / 2)}" rpy="0 0 0"/> <!--lidar'ı robotun biraz üzerine yerleştirebilmke için gerekir-->
    </joint>

     <!-- Gazebo kamera sensörü -->
    <gazebo reference="lidar_link">
        <sensor name="lidar_sensor" type="ray">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>30.0</update_rate>  <!-- Kamera FPS oranı -->
            
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples> <!--etraftaki yani toplam 360 dereceden toplam 720 adet nokta alıyor-->
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle> <!--taradığı alanı ifade eder ve bu 360 derece dönen 2 boyutlu bir lidarın özelliğidr.-->
                        <max_angle>3.14</max_angle> <!--taradığı alanı ifade eder ve bu 360 derece dönen 2 boyutlu bir lidarın özelliğidr-->
                    </horizontal>
                </scan>
                <range> <!--lidar'ın; min, max ve çözünürlüğünü girdiğim değerleri range etiketi arsında yazarım. .-->
                    <min>0.1</min>
                    <max>30.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>

            <!-- ROS ile kamera verilerini yayınlamak için plugin -->
            <plugin name="lidar_controller" filename="libgazebo_ros_ray_sensor.so">
                <output_type>sensor_msgs/LaserScan</output_type> <!--lidar veya lazer sensor_msgs/LaserScan ile haberleşir. -->
            </plugin>
        </sensor>
    </gazebo>

</robot>
