<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://ros.org/wiki/xacro">

 <!-- Kamera boyutları için xacro değişkenleri -->
    <xacro:property name="camera_width" value="0.1"/>
    <xacro:property name="camera_length" value="0.01"/>
    <xacro:property name="camera_height" value="0.05"/>

    <link name = "camera_link" >
        <visual>
            <geometry>
                <box size = "${camera_length} ${camera_length} ${camera_height}" />  <!--with, length, heigt--> 
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
            <material name = "Gazebo/Grey"/>
        </visual>

        <collision>
            <geometry>
                <box size = "${camera_length} ${camera_length} ${camera_height}" />  <!--with, length, heigt--> 
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
        </collision>

        <xacro:box_inertia m = "5.0" l = "${2*base_length}" 
                                     w = "${2*base_width}" 
                                     h = "${2*base_height}" 
                                     xyz = "0 0 0"
                                     rpy = "0 0 0" /> <!--xyz konumu ifade ederken rpy oryantasyonu ifade ediyor.-->
                                     <!--bu değerleri bir miktar arttırdığımızda eylemsizlik momenti artacağı için daha stabil bir durum
                                     elde etmiş olurum. 2* genişleterek bu durumu düzeltemiş olurum.-->
    </link>

       <!-- Kamera ve base_link arasında sabit bağlantı (joint) -->
    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="0.3 0 0" rpy="0 0 0"/>
    </joint>

     <!-- Gazebo kamera sensörü -->
    <gazebo reference="camera_link">
        <sensor name="camera_sensor" type="camera">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>30.0</update_rate>  <!-- Kamera FPS oranı -->
            <camera>
                <horizontal_fov>1.047</horizontal_fov> <!-- Görüş açısı -->
                <image>
                    <width>640</width>  <!-- Çözünürlük genişliği -->
                    <height>480</height> <!-- Çözünürlük yüksekliği -->
                    <format>R8G8B8</format> <!-- Görüntü formatı -->
                </image>
                <clip>
                    <near>0.1</near>  <!-- Minimum görüş mesafesi -->
                    <far>100</far>    <!-- Maksimum görüş mesafesi -->
                </clip>
            </camera>

            <!-- ROS ile kamera verilerini yayınlamak için plugin -->
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <always_on>true</always_on>
                <update_rate>30.0</update_rate>
                <camera_name>camera_sensor</camera_name>
                <image_topic_name>/camera/image_raw</image_topic_name> <!-- ROS topic ismi -->
                <camera_info_topic_name>/camera/camera_info</camera_info_topic_name>
                <frame_name>camera_link</frame_name>
                <hack_baseline>0.07</hack_baseline>
            </plugin>
        </sensor>
    </gazebo>

</robot>
